/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mM3qXW3HhZc
 */
"use client";
import {Label} from "@/components/ui/label";
import {Input} from "@/components/ui/input";
import {SelectValue, SelectTrigger, SelectItem, SelectContent, Select} from "@/components/ui/select";
import {Textarea} from "@/components/ui/textarea";
import {Button} from "@/components/ui/button";
import {FormEvent, useState} from "react";
import {useRouter} from "next/navigation";
import {addPost} from "@/lib/apiUtil";
import {User} from "next-auth";

export function NewPostForm({user}: {user: User}) {
    const categories = ["Food", "Technology", "Movies & TV shows", "Music"] as const;
    const [title, setTitle] = useState("");
    const [category, setCategory] = useState("Food");
    const [text, setText] = useState("");
    const router = useRouter();

    const submit = (e: FormEvent) => {
        e.preventDefault();
        console.log(user.id);
        const post = {
            title,
            category,
            text,
            userId: user.id,
            userName: user.name || "Anonymous",
        };
        addPost(post)
            .then((data) => router.push(`/posts/${data.postId}`))
            .catch((err) => console.log(err));
    };

    return (
        <div className="dark bg-zinc-800 text-white p-6 rounded-lg w-1/2">
            <h2 className="text-2xl font-bold mb-4">Create a Blog Post</h2>
            <form className="space-y-4" onSubmit={submit}>
                <div className="flex flex-col space-y-1.5">
                    <Label className="text-lg" htmlFor="title">
                        Title
                    </Label>
                    <Input
                        className="text-base bg-zinc-900 border-zinc-700"
                        id="title"
                        placeholder="Enter your blog title"
                        onChange={(e) => setTitle(e.target.value)}
                        required
                    />
                </div>
                <div className="flex flex-col space-y-1.5 ">
                    <Label className="text-lg" htmlFor="category">
                        Category
                    </Label>
                    <Select onValueChange={(value) => setCategory(value)} required>
                        <SelectTrigger className="text-base bg-zinc-900 border-zinc-700" id="category">
                            <SelectValue placeholder="Select a category" />
                        </SelectTrigger>
                        <SelectContent position="popper" className="border-zinc-700 bg-zinc-700 text-white ">
                            {categories.map((category) => (
                                <SelectItem value={category} key={category} className="cursor-pointer hover:bg-zinc-600 rounded-md">
                                    {category}
                                </SelectItem>
                            ))}
                        </SelectContent>
                    </Select>
                </div>
                <div className="flex flex-col space-y-1.5">
                    <Label className="text-lg" htmlFor="content">
                        Content
                    </Label>
                    <Textarea
                        className="text-base min-h-[200px] text-white bg-zinc-900 border-zinc-700"
                        id="content"
                        placeholder="Write your blog post here..."
                        onChange={(e) => setText(e.target.value)}
                        required
                    />
                </div>
                <Button className="self-end bg-white text-black hover:bg-gray-300 transition-colors font-semibold" type="submit">
                    Publish
                </Button>
            </form>
        </div>
    );
}
